
baseURL = "https://eu.communityovercode.org"
canonifyURLs = false
title = "Community Over Code Europe"
description = "Community Over Code Europe is the annual gathering in Europe of the Apache Software Foundation community."
enableRobotsTXT = true
RemovePathAccents = true
DefaultContentLanguage = "en"

theme = "coceu"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"


############################## navigation ###############################
[menu]


[[menu.main]]
    identifier = "category"
    name = "About"
    url = "/about"
    weight = 2
  [[menu.main]]
    identifier = "category1"
    name = "About Community Over Code"
    url = "/about"
    parent = "category"
    weight = 1
  [[menu.main]]
    identifier = "category2"
    name = "About the ASF"
    url = "/about-the-asf"
    parent = "category"
    weight = 2


[[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 7




# Everything below this are Site Params

[params]
description = "Community Over Code Europe is the annual gathering in Europe of the Apache Software Foundation community."
logo = "/images/coc-logo-color.svg"
home = "Home"
privacy_policy = "/privacy"
footer_text = "Community Over Code operates under the terms of [The ASF Code of Conduct](https://apache.org/foundation/policies/conduct)."

# First one is picked as the Twitter card image if not set on page.
images = ["/images/card.jpg"]
start_date = "2024-06-03T09:00-05:00"
end_date = "2024-06-05T17:00-05:00" 

[params.hero]
text = "June 3-5, 2024. Bratislava, Slovakia."

[params.hero.cta1]
text = "Submit your proposal"
link = "https://sessionize.com/coceu-2024/"

# Navigation button
[params.navigation_button]
enable = false
label = "Tickets"
link = "/tickets"


[params.links]
[[params.links.media]]
    name = "Email us"
    url = "mailto:planners@apachecon.com?subject=[EU]"
    icon = "fa fa-envelope"
[[params.links.media]]
    name = "Slack"
    url = "https://s.apache.org/apachecon-slack"
    icon = "fab fa-slack"
[[params.links.media]]
    name = "Watch us on YouTube"
    url = "https://www.youtube.com/@communityovercode"
    icon = "fab fa-youtube"

[[params.links.footer]]
    name = "Code of Conduct"
    url = "/coc"
[[params.links.footer]]
    name = "Accessibility"
    url = "/accessibility"
[[params.links.footer]] 
    name = "Privacy Policy"
    url = "/privacy"
[[params.links.footer]]
    name = "Organizers"
    url = "/team"
[[params.links.footer]]
    name = "Prospectus"
    url = "https://drive.google.com/file/d/1WYVv7Q7nQcljtYXRsWdj7KCaZvg2Gg4l/view"


[permalinks]
tags = "/blog/tags/:slug/"
posts = "/:year/:month/:title/"

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "/plugins/bootstrap.min.css"

[[params.plugins.css]]
link = "/plugins/bootstrap-table.min.css"

[[params.plugins.css]]
link = "/plugins/fontawesome.css"

[[params.plugins.css]]
link = "/plugins/swiper-bundle.min.css"

# JS Plugins
[[params.plugins.js]]
link="/plugins/bootstrap.bundle.min.js"

[[params.plugins.js]]
link="/plugins/bootstrap-table.min.js"

[[params.plugins.js]]
link="/plugins/swiper-bundle.min.js"

[[params.plugins.js]]
link="/plugins/bootstrap-table.min.js"
